;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = #000000
;background-alt = #000000
;foreground = #FFFFFF
background = #282A2E
foreground = #C5C8C6
red = #CC6666
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 32pt
radius = 6

dock = true 
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMonoNL Nerd Font Propo Medium Italic;size=12
font-1 = Font Awesome 6 Free:style=Regular;size=12
font-2 = "Symbols Nerd Font Mono:size=12"

modules-left = i3 
modules-center = date
modules-right = filesystem pulseaudio cpu memory temp wlan bluetooth battery 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

override-redirect = false

[module/i3]
type = internal/i3
show-urgent = true
index-sort = true
enable-click = true
fuzzy-match = true
pin-workspaces = true

ws-icon-0 = 1;󰎤
ws-icon-1 = 2;󰎧
ws-icon-2 = 3;󰎪
ws-icon-3 = 4;󰎭
ws-icon-4 = 5;󰎱
ws-icon-5 = 6;󰎳
ws-icon-6 = 7;󰎶
ws-icon-7 = 8;󰎹

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.primary}

label-focused = %icon%
label-focused-font = 5
label-focused-foregroun = ${colors.primary}
label-focused-padding = 1

label-unfocused = %icon%
label-unfocused-font = 5
label-unfocused-foreground = ${colors.subtext0}
label-unfocused-padding = 1

label-visible = %icon%
label-visible-padding = 1

label-urgent = %icon%
label-urgent-font = 5
label-urgent-foreground = ${colors.red}
label-urgent-padding = 1

[module/systray]
type = internal/tray

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground= ${colors.primary}
label-volume-padding-left=2
label-volume-padding-right=2

label-muted = [ 󰖁 ]  muted
label-muted-foreground = ${colors.red}
label-muted-padding=2

[module/filesystem]
type = internal/fs

mount-0 = /
fixed-values = true
warn-percentage = 75
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
format-mounted = <label-mounted>

[module/memory]
type = internal/memory
interval = 10
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
click-left = exec 

[module/bluetooth]
type = custom/script
exec = ~/.local/bin/bluetooth.sh
interval = 2
click-left = exec blueman-manager
click-right = ~/.local/bin/toggle_bluetooth.sh
format-padding = 1
format-background = #000000
format-foreground = #ffffff

[module/wlan]
inherit = network-base
interface-type = wireless
format-connected= %{F#F0C674}  %{F-}<label-connected>
; label-connected = %{F#F0C674}%ifname%%{F-} %essid% 
label-connected = %essid% 
click-left = exec nm-connection-editor
click-right = exec nm-connection-editor


[module/eth]
inherit = network-base
interface-type = wired

format-connected = <label-connected> aaa
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip% 

[module/date]
type = internal/date
interval = 1
format-prefix = " "
format-prefix-foreground=${colors.primary}

date = %d (%A) %H:%M
date-alt = %d-%m-%Y %H:%M

label = %date%
label-foreground = ${colors.primary}
label-padding-left=2
label-padding-right=2

[module/temp]
type = internal/temperature
interval = 3
thermal-zone = 0
hwmon-path = /sys/class/hwmon/hwmon1/temp1_input
base-temperature = 36 
warn-temperature = 60
units = true

format =<label>
format-prefix = " "
format-prefix-foreground= ${colors.primary}

label = %temperature-c%
label-foreground = ${colors.primary}
label-padding-left=2
label-padding-right=2

format-warn-prefix = " "
format-warn-prefix-foreground= ${colors.red}

label-warn = %temperature-c%
label-warn-foreground = ${colors.red}
label-warn-padding-left=2
label-warn-padding-right=2

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
